# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\GitHub\process-monitor\cron_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CRON(object):
    def setupUi(self, CRON):
        CRON.setObjectName("CRON")
        CRON.resize(380, 300)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(CRON.sizePolicy().hasHeightForWidth())
        CRON.setSizePolicy(sizePolicy)
        CRON.setMinimumSize(QtCore.QSize(380, 300))
        CRON.setMaximumSize(QtCore.QSize(380, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        CRON.setFont(font)
        self.slider_m = QtWidgets.QSlider(CRON)
        self.slider_m.setGeometry(QtCore.QRect(10, 110, 251, 22))
        self.slider_m.setMaximum(60)
        self.slider_m.setSingleStep(5)
        self.slider_m.setOrientation(QtCore.Qt.Horizontal)
        self.slider_m.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_m.setObjectName("slider_m")
        self.sb_m = QtWidgets.QSpinBox(CRON)
        self.sb_m.setGeometry(QtCore.QRect(280, 110, 81, 22))
        self.sb_m.setObjectName("sb_m")
        self.slider_h = QtWidgets.QSlider(CRON)
        self.slider_h.setGeometry(QtCore.QRect(10, 180, 251, 22))
        self.slider_h.setMaximum(24)
        self.slider_h.setOrientation(QtCore.Qt.Horizontal)
        self.slider_h.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.slider_h.setObjectName("slider_h")
        self.sb_h = QtWidgets.QSpinBox(CRON)
        self.sb_h.setGeometry(QtCore.QRect(280, 180, 81, 22))
        self.sb_h.setObjectName("sb_h")
        self.lbl_title = QtWidgets.QLabel(CRON)
        self.lbl_title.setGeometry(QtCore.QRect(0, 30, 371, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.label = QtWidgets.QLabel(CRON)
        self.label.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(CRON)
        self.label_2.setGeometry(QtCore.QRect(10, 160, 81, 21))
        self.label_2.setObjectName("label_2")
        self.btn_set = QtWidgets.QPushButton(CRON)
        self.btn_set.setGeometry(QtCore.QRect(130, 230, 221, 51))
        self.btn_set.setObjectName("btn_set")
        self.btn_reset = QtWidgets.QPushButton(CRON)
        self.btn_reset.setGeometry(QtCore.QRect(30, 230, 81, 51))
        self.btn_reset.setObjectName("btn_reset")

        self.retranslateUi(CRON)
        QtCore.QMetaObject.connectSlotsByName(CRON)

    def retranslateUi(self, CRON):
        _translate = QtCore.QCoreApplication.translate
        CRON.setWindowTitle(_translate("CRON", "Form"))
        self.lbl_title.setText(_translate("CRON", "CRON JOB"))
        self.label.setText(_translate("CRON", "Minutes:"))
        self.label_2.setText(_translate("CRON", "Hours:"))
        self.btn_set.setText(_translate("CRON", "OK"))
        self.btn_reset.setText(_translate("CRON", "Reset"))
