# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\jacky\test_code\process-monitor-main\interface.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 501)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(401, 501))
        Form.setMaximumSize(QtCore.QSize(401, 501))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        Form.setFont(font)
        self.btn_event = QtWidgets.QPushButton(Form)
        self.btn_event.setGeometry(QtCore.QRect(10, 430, 380, 61))
        self.btn_event.setObjectName("btn_event")
        self.lineEdit = QtWidgets.QLineEdit(Form)
        self.lineEdit.setGeometry(QtCore.QRect(25, 90, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.lbl_title = QtWidgets.QLabel(Form)
        self.lbl_title.setGeometry(QtCore.QRect(0, 0, 401, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName("lbl_title")
        self.lbl_title2 = QtWidgets.QLabel(Form)
        self.lbl_title2.setGeometry(QtCore.QRect(0, 60, 401, 20))
        self.lbl_title2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title2.setObjectName("lbl_title2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(75, 40, 251, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(25, 170, 351, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lbl_title2_2 = QtWidgets.QLabel(Form)
        self.lbl_title2_2.setGeometry(QtCore.QRect(0, 140, 401, 20))
        self.lbl_title2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title2_2.setObjectName("lbl_title2_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn_event.setText(_translate("Form", "Start"))
        self.lineEdit.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">Enter the PID of program</span></p></body></html>"))
        self.lbl_title.setText(_translate("Form", "Process Monitor"))
        self.lbl_title2.setText(_translate("Form", "Process PID Number"))
        self.lineEdit_2.setToolTip(_translate("Form", "<html><head/><body><p><span style=\" font-size:9pt;\">Enter the PID of program</span></p></body></html>"))
        self.lbl_title2_2.setText(_translate("Form", "Your LINE Token"))
